### ISSUE TITLE
Why yield test_triple in validation_data method?

### ISSUE THREAD

**Issue by ZichaoHuang** [bxshi/ProjE#1]
I think the `validation_data` method should yields `self.__valid_triple`, but in [ProjE_softmax.py](https://github.com/bxshi/ProjE/blob/master/ProjE_softmax.py#L76) it yields `self.__test_triple`, why?

**Comment by bxshi** [comment]
Good catch! I think that is a mistake... Thanks for pointing it out! Feel free to make a PR our I'll correct it later :)
