### ISSUE TITLE
Question about sampled_softmax

### ISSUE THREAD

**Issue by ZichaoHuang** [bxshi/ProjE#4]
Hi, it's me again :)
I wonder what's the purpose of **rescale** in the `sampled_softmax` function?

**Comment by bxshi** [comment]
Hi no worries. I think it is some poorly designed numerical trick to help preventing numerical instability when calculating the `exp`. You can remove the `rescale` since I already have `tf.clip_by_value` elsewhere.

Thank you so much for helping me improving the quality of the code!

**Comment by ZichaoHuang** [comment]
OK, thanks!
