### ISSUE TITLE
about the parameter size

### ISSUE THREAD

**Issue by ocsponge** [bxshi/ProjE#7]
hi, @bxshi, in your paper, you said 

> Therefore, compared to simple models like TransE, ProjE only increases the number of parameters by 5k + 1, where 1, 4k, and k are introduced as the projection bias, combination weights, and combination bias respectively

but the combination weights **De** and **Dr** both are k*k diagonal matrices, each of them should have k parameters so that there would be 2k, why 4k in your paper?

**Comment by ocsponge** [comment]
forgive my poor English :)

**Comment by bxshi** [comment]
Hi, tail prediction and head prediction are using two sets of De and Dr.
Hence 2k + 2k = 4K.

Best,

**Comment by ocsponge** [comment]
so for the relation prediction task, there would be another 2k parameters which is different from head prediction(2k) and tail prediction task(2k)? is that correct?

**Comment by bxshi** [comment]
Right

**Comment by ocsponge** [comment]
thank you for your quick reply！
